mkbuilddir: compdll
	powershell -command rm *.o

compdll: linkobjs
	gcc -s -shared swapi.o -o swapi.dll -lcomdlg32

linkobjs: window.o destroyelem.o menus.o msgbox.o filepopup.o button.o image.o textfield.o
	ld -relocatable window.o destroyelem.o menus.o msgbox.o filepopup.o button.o image.o textfield.o -o swapi.o

all: 

window.o:
	gcc -I. -c src\Windows\window.c

destroyelem.o:
	gcc -I. -c src\Elements\destroyelem.c

menus.o:
	gcc -I. -c src\Elements\menus.c

msgbox.o:
	gcc -I. -c src\Windows\msgbox.c

filepopup.o:
	gcc -I. -c src\Windows\filepopup.c
	
button.o:
	gcc -I. -c src\Elements\button.c

image.o:
	gcc -I. -c src\Elements\image.c

textfield.o:
	gcc -I. -c src\Elements\textfield.c